name: test

on:
  schedule:
    # 北京时间 10:45 和 10:50（UTC 02:45 和 02:50）
    - cron: '45,50 2 * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print test
        run: echo "test 当前时间是 $(date '+%Y-%m-%d %H:%M:%S')"
