name: test

on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print test
        run: echo "test 当前时间是 $(date '+%Y-%m-%d %H:%M:%S')"
